export const JOB_POSITION_HISTORY_REQUEST = "JOB_POSITION_HISTORY_REQUEST";
export const JOB_POSITION_HISTORY_SUCCESS = "JOB_POSITION_HISTORY_SUCCESS";
export const JOB_POSITION_HISTORY_ERROR = "JOB_POSITION_HISTORY_ERROR";